adaptlearning/adapt-contrib-spoor

js/adapt-contrib-spoor.js
Added the following code in the develop branch, as per @oliverfoster.
```javascript
if (this.data._isEnabled === false) return;
```
This should work for Adapt core.  For more complicated cases where scormWrapper gets called directly (from a component or extension), we should look at adding an _isEnabled variable in adapt-contrib-spoor.js so we don't have to continuously check *if ( this.data._isEnabled === false)* or *if ( this.data._isEnabled === true)*, as per @moloko.
=> Issues/#49 - Add ability to disable spoor via config.json.

js/serializers/scormSuspendDataSerializer.js
* Update to always choose to convert to a decimal array when the numeric array being saved contains a decimal value.
When a text input with 2 input boxes has answers of  1 correct and 1 incorrect it produces the array > [0,-1]
Arrays must have a common type in order to be saved in this format. Therefore a numeric array must be normalized before it is saved.
As decimal is the only numeric type (from half, byte, short, long and decimal) to accommodate negative numbers:
[0, -1] would be a decimal array
[half, decimal] > [decimal, decimal]
have forced this behaviour
=> Decimal array fix

js/adapt-contrib-spoor.js
* Allows for language to be saved / restored before the course data has loaded
* Allows for multiple language folders and pre-load language selection such as > https://github.com/cgkineo/adapt-languageSelection/blob/master/js/langsel.js
=> Fix: initialize at config load not course load

js/serializers/questions.js
* doesn't restore data to same set of components, uses all components in block to restore to rather than just the question components this pushes off the block locations
#83
=> fix: use only questions in capture and release

js/adapt-contrib-spoor.js, js/adapt-stateful-session.js
If the spoor extension is not enabled, the code should not throw errors because the relevant configruation does not exists.  I've added some checks for this.
=> Fixes #98, adds defensive programming

js/adapt-contrib-spoor.js, js/scorm/wrapper.js
`_advancedSettings` are not set (fixes ([https://adaptlearning.atlassian.net/browse/ABU-1076](ABU-1076))
wrapper.js: refactor `setVersion` so that it uses the pre-existing `isSCORM2004` function
=> adapt-contrib-spoor.js: ensure that `setVersion` is called even when 

example.json, js/adapt-contrib-spoor.js, js/scorm/wrapper.js, properties.schema
Add silent property that will prevent (when true) appearance of any error popups along with debug window without disabling spoor. Useful when the same build must be used in LMS and non-LMS environment.
=> The "silent" property

js/serializers/default.js
Allow spoor to restore component completion if block is already complete. isOptional fix.
=> issue-957: isoptional and component completion restore

js/scorm/wrapper.js
Ensure the "S" is included when the output is a whole number of seconds. 
Also some slight formatting changes.
=> fix for issue #986

js/adapt-stateful-session.js
if the question component hasn't been setup for it (see https://github.com/adaptlearning/adapt_framework/issues/955)
=> amend adapt-stateful-session.js so that it won't attempt to do interaction tracking

js/scorm/API.js
from https://github.com/pipwerks/scorm-api-wrapper
main difference is that 'set' calls are logged to the console now as well as 'get' calls
=> update to latest version of the pipwerks code

README.md, example.json, js/adapt-contrib-spoor.js, properties.schema
Uses the Page Visibility API to perform a SCORM commit whenever a course becomes hidden.
In my tests on Moodle, the `visibilitychange` event was firing successfully in the following:
* iOS 8
* iOS 9
* Android 6
* Safari 9
* Firefox 47
The event wasn't so consistent in:
* Chrome 51
* Edge 25
* IE 11
Although the original link mentions also implementing a `pagehide` listener, the `unload` handler was firing successfully in the cases where `pagehide` worked.
Original issue: https://github.com/adaptlearning/adapt_framework/issues/873.
=> Add visibilitychange listener

js/scorm/wrapper.js
...when there's fractions of a second (see [#1222](https://github.com/adaptlearning/adapt_framework/issues/1222))
also prevents the time output from being "P0S" which isn't valid - now it will output the valid value "PT0S" instead
=> amends to convertToSCORM2004Time to stop it from adding in an additional "S"

js/scorm/wrapper.js, required/offline_API_wrapper.js
Will help quickly determine if user has linked to incorrect launch file when deploying to LMS. This happened recently - a client used an uploader tool which clearly did not abide the settings in the imsmanifest.xml. index.html was selected as the launch file rather than index_lms.html and therefore no data was reported to the LMS.
**Expected usage**: tracking problems reported on LMS. Enable debugging in config, redeploy and first line of debug log will reveal if the appropriate tracking API is being used.
=> Added warning to debug log if using offline API.

js/adapt-contrib-spoor.js
Another component/extension in a course may have already called finish against SCORM (close button for example).
This prevent an 'LMS is not longer connected' message box.
=> Wrapped SCORM finish in finishCalled check

bower.json, js/scorm/wrapper.js
as per https://github.com/adaptlearning/adapt_framework/issues/1363
if you want to test you'll need to publish a course as SCORM 2004 with `_tracking._shouldRecordInteractions` set to `true` in your `_spoor` config - or you could just have a look at the version I [uploaded to SCORM Cloud](https://cloud.scorm.com/sc/InvitationConfirmEmail?publicInvitationId=308a4475-22cb-4b52-8c72-03e5d6a42272) ;-)
To test, answer a few questions and check you don't get any errors about cmi.interactions.n.timestamp being in the wrong format
=> amend getISO8601Timestamp to use date.toISOString

js/scorm/wrapper.js
The ```submitScore``` method will also need to take this into account so it isn't restricted to 0-100 scores.
=> Amended wrapper.js for adaptlearning/adapt_framework#1413. 

README.md, bower.json, js/adapt-stateful-session.js, required/offline_API_wrapper.js
part of https://github.com/adaptlearning/adapt_framework/issues/1040
=> have spoor overwrite the hard-coded 'learner info' data with real data

required/offline_API_wrapper.js
before being written to the cookie, so as to avoid a bug in Safari for iOS v10 (https://github.com/adaptlearning/adapt_framework/issues/1589)
=> ensure commas are url-encoded

js/adapt-contrib-spoor.js
when the course window starts unloading
see https://github.com/adaptlearning/adapt_framework/issues/1625
=> amend to ensure that the visibilitychange event listener is removed

README.md, bower.json, js/adapt-contrib-spoor.js
The document.removeEventListener function isn't supported in IE 8.
=> Fixes #1767, problem with IE 8 failing to commit tracking data

bower.json, js/adapt-stateful-session.js, properties.schema
After some discussion it was agreed that this is a more sensible default.  Also updated the label and help text for the authoring tool for more clarity.
=>  Resolves #1875, defaults _shouldStoreResponses to true 

README.md, bower.json, js/adapt-stateful-session.js
fixes https://github.com/adaptlearning/adapt_framework/issues/2046 by letting the compatibility code that's already present in questionView handle redirecting to the model/view version of the function as needed (as we were doing before)
note that when we come to drop that compatibility code from questionView - which will be quite a way off yet! - all that we'll need to change in spoor is to amend `onQuestionRecordInteraction` to this:
```js
var questionModel = questionView.model;
var responseType = questionModel.getResponseType();
// if responseType doesn't contain any data, assume that the question component hasn't been set up for cmi.interaction tracking
if(_.isEmpty(responseType)) return;
var id = questionModel.get('_id');
var response = questionModel.getResponse();
var result = …
```
=> reverts changes made in #171

README.md, example.json, js/adapt-contrib-spoor.js, js/scorm/wrapper.js, properties.schema
Fixes [#2458](https://github.com/adaptlearning/adapt_framework/issues/2458)
- Add fields to advanced settings that allow the user to define exit codes when course is completed, and when it is incomplete
- Support for SCORM 1.2 and 2004
=> Define Exit Status in Advanced Settings

js/serializers/questions.js, properties.schema
[#2747](https://github.com/adaptlearning/adapt_framework/issues/2747)
Requires [#2748](https://github.com/adaptlearning/adapt_framework/pull/2748) to framework for testing.
Built atop of #190, the old question state serialiser couldn't handle the more complicated data structure.
* All question states are saved all of the time, rather than just complete questions. All states would normally only be stored by the completion of the course.
* Questions with `_isResetOnRevisit = truthy` are saved as attempt states can be more useful here. The new serialiser is much more efficient and stable and is able to capture this new information and store all of the current and new data in a smaller suspend data footprint.
* Save and restores `_attemptStates` attributes across sessions
* Added …
=> issue/2747 Added _attemptStates save and restore

js/adapt-offlineStorage-scorm.js, js/adapt-stateful-session.js
[#2754](https://github.com/adaptlearning/adapt_framework/issues/2754)
* Backend for `Adapt.offlineStorage.save()` to force state saving
[#2755](https://github.com/adaptlearning/adapt_framework/issues/2755)
* Backend for `Adapt.offlineStorage.serialize()` and `Adapt.offlineStorage.deserialise()`
Built ontop of #190 and #192
Requires [#2757](https://github.com/adaptlearning/adapt_framework/pull/2757)
=>  issue/2754-2755 Added save, serialize and deserialize

js/adapt-offlineStorage-scorm.js, js/adapt-stateful-session.js
[#2756](https://github.com/adaptlearning/adapt_framework/issues/2756)
* Reduced data usage
Built ontop of #192  and #190 
Note:
The course state will print out in the console when changed:
`
INFO: course._isComplete: true, course._isAssessmentPassed: true, BlockCompletion: 1111111110111110101
`
In order to manually deserialize the course state from one course in another, take the suspend data log:
`
{"lang":"en","a11y":false,"b":{"a-25":"i-ooRUixFyMA"},"c":"oAOP/93B","q":"oAIRInoEHCAh/kQGHC9EAjwxEEiegQgICH-Mgw4XogEeGGRInoEJCAh/h/YAAgAADDheiAR4YP7AAEAABInoEKCAh/j9IAgYcL0QCPDD9IAhInoELCAhfh9QgGHC9EAjw-oQJE9AhgAEAAACRPQIaEBD/KwGHC9EAjwxWCRPQIcEBD/KgGHC9EAjwxUCRPQIeEBD/IwMOF6IBHhiMJE9AiAAEAAACRPQIiEBD/IwMOF6IBHhiMJE9AigAEDAAYcL0QCPDEQSJ6BFQAIGAAw4XogEeGGRInoEWAAgYADDheiAR4YP7AAEAABInoEXAAgYADD …
=> issue/2756 Reduced data usage

js/serializers/ComponentSerializer.js
[#2896](https://github.com/adaptlearning/adapt_framework/issues/2896)
* Corrected the code to pick up and restore the `_attemptStates` property properly
=> issue/2896 Bugfix for attemptStates save + restore

js/scorm/logger.js
[#2915](https://github.com/adaptlearning/adapt_framework/issues/2915)
* Global reference to Logger class
=> issue/2915 Re-added Logger global reference for debug window

js/adapt-stateful-session.js, js/serializers/ComponentSerializer.js
[#2910](https://github.com/adaptlearning/adapt_framework/issues/2910)
* Re-added `_shouldStoreResponses: false` to keep `_isComplete` values
* Re-added `_shouldStoreAttempts: false` such that it can be disabled
* Warns with conflicting `_shouldStoreAttempts: true` and `_shouldStoreResponses: false`
* Derives the deserialization `_shouldStoreResponses` from the saved data to allow correct deserialization of existing data
* Skips restoration of missing tracking ids
=> issue/2910 Re-added _shouldStoreResponses=false and _shouldStoreAttempts

example.json, js/scorm/error.js, js/scorm/wrapper.js
[#1333](https://github.com/adaptlearning/adapt_framework/issues/1333)
[#1238](https://github.com/adaptlearning/adapt_framework/issues/1238)
* Error objects with codes and error data
* Default messages and translatable overrides
* Used an `_isCancellable: false` notify to display `CLIENT_COULD_NOT_CONNECT` errors
=> issue/1333 Added error abstraction

js/adapt-stateful-session.js
When publishing a course with Spoor and the setting _commitOnStatusChange set to false, it is not picked up and set during runtime.
It appears as though the if statement around the setting assignment only checks for true values, and as the default value is already true[1], it can never be set to false.
This got us in our older LMS platform which requires this setting to be set to false.
fixes https://github.com/adaptlearning/adapt_framework/issues/2943
[1] https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/js/scorm/wrapper.js#L31
=> Allow _commitOnStatusChange setting to be false

README.md, bower.json, js/scorm/wrapper.js
so that it returns `false` if the error code is 401 and `true` if it's not
fixes https://github.com/adaptlearning/adapt_framework/issues/2991
=> reverse logic of return statement in isSupported

js/adapt-stateful-session.js
if the settings are missing from config.json
fixes https://github.com/adaptlearning/adapt_framework/issues/2994
=> ensure that this._shouldStoreResponses and this._shouldStoreAttempts don't get set to undefined 

js/adapt-stateful-session.js
fixes https://github.com/adaptlearning/adapt_framework/issues/3138
* Made the `printCompletionInformation` function aware of the location of `isComplete` when `shouldStoreResponses` is `false` in the config.json
=> issue/3138 printCompletionInformation shouldStoreResponses awareness

js/serializers/ComponentSerializer.js
fxies https://github.com/adaptlearning/adapt_framework/issues/3204
* Check for `_isTrackable: false`
* Warn for missing components rather than fail
=> issue/3204 Added check for _isTrackable and skip bug warn for missing components

bower.json, schema/config.schema.json, schema/course.schema.json
Part of adaptlearning/adapt_framework#2704.
=> Add support for authoring tool 1

js/adapt-contrib-spoor.js, js/adapt-offlineStorage-scorm.js, js/adapt-stateful-session.js, js/scorm/wrapper.js, js/serializers/ComponentSerializer.js
requires https://github.com/adaptlearning/adapt-contrib-core/pull/84
part of https://github.com/adaptlearning/adapt_framework/issues/2799
* Use `offlineStorage`, `data`, `logging` and `notify` directly
* Linting issues
=> issue/2799 Remove redundant behaviour

js/adapt-offlineStorage-scorm.js, js/adapt-stateful-session.js
fixes #232 
part of https://github.com/adaptlearning/adapt-contrib-core/pull/111
* `offlineStorage.clear()` backend
* Event attachment/detachment and function binding
=> issue/232 Added offlineStorage.clear

README.md, example.json, properties.schema, required/offline_API_wrapper.js, schema/config.schema.json
#247
1. make the reset button available so that we may clear tracking data easily
2. allow shift-clicking the reset button to relaunch but preserve tracking data
3. when reset is clicked simulate the user closing and relaunching the course (so no hash/query on the URL)
4. style the reset button in a familiar manner
=> Improve use of scorm_test_harness.html (fixes #247)

properties.schema
Fixes: #254 
* Escaped quotation marks in the help section of _setCompletedWhenFailed
=> Fix: escaped double quotes in _setCompletedWhenFailed help msg (fixes #254)

js/adapt-stateful-session.js, js/scorm/Connection.js, js/scorm/wrapper.js
Sub pr for https://github.com/adaptlearning/adapt-contrib-spoor/pull/270
* Moved wrapper config setup into the wrapper, removing need for `connectionTest` config object
* Call `tracking:connectionError` from one location only, simplifying its relationship to other bits of code
* Removed repetitive `bind(this)` to singular versions
=> Slight refactor

README.md, example.json, js/adapt-stateful-session.js, js/scorm/Connection.js, js/scorm/wrapper.js, properties.schema, required/connection.json, schema/config.schema.json
Fixes #268 
* Added feature to test the network connection when transferring data to the LMS API.
* Raises an error if the connection is lost.
Further error handling can be utlised with [adapt-contrib-trackingErrors](https://github.com/adaptlearning/adapt-contrib-trackingErrors).
=> New: network connection test

js/scorm/wrapper.js
fixes #274 
* Default, missing config error correction
Actual defaults come from class constructor:
https://github.com/adaptlearning/adapt-contrib-spoor/blob/4a727367fc7a4ac531033b190ef2228b59c415a5/js/scorm/Connection.js#L5-L10
=> Fix: Undefined settings error

js/adapt-stateful-session.js
fixes https://github.com/adaptlearning/adapt-contrib-spoor/issues/271
* Correct printCompletionInformation string creation, off by one error in array length
=> Fix: Correct printCompletionInformation string creation

README.md, example.json, js/adapt-stateful-session.js, js/scorm/cookieLMS.js, properties.schema, schema/config.schema.json
fixes #277 
* `config.json:_spoor._advancedSettings._uniqueInteractionIds = false` to allow control over unique `cmi.interactions.n.id` entries
* Switched cookeLMS to store values in nested objects and arrays rather than as a hash of key value pairs (backward compatible), such that it's possible to properly test the `cmi.interactions` property. In the future `cmi.objectives`, `cmi.comments_from_learner` and `cmi.interactions.n.objectives.m` can be easily added to the `scorm_test_harness.html` cookie lms as a result
The cookie lms will look like this now:
Instead of this:
[SCORM 2004 v4 Spec, RTE-4-5](https://github.com/adaptlearning/scorm_docs/blob/master/SCORM%202004/4th%20Edition/SCORM_2004_4ED_v1_1_RTE_20090814.pdf):
Only support for `cmi.interactions` has been added to the testing …
=> New: Added _uniqueInteractionIds, testing support for cmi.interactions

js/adapt-contrib-spoor.js, js/scorm/wrapper.js
#284 
Linked to Jest testing (https://github.com/adaptlearning/adapt_framework/pull/3383)
* Return early added to wrapper.js if Adapt.course does not exist
* jquery.keycombo changed from require to import
=> Fix: wrapper.js & adapt-contrib-spoor updated to work with Jest testing. (fixes #284)

js/adapt-stateful-session.js, required/log_output.html
Partly fixes [FW3481](https://github.com/adaptlearning/adapt_framework/issues/3481)
* Added a 'pagehide' listener to backup the soon-to-be-deprecated 'unload' event
=> fix: Adding a pagehide listener to cover bases when unload becomes deprecated

js/adapt-stateful-session.js
fixes #294 
Add a check that the LMS supports cms.interactions._count to prevent error message appearing to user
1. Create a course that includes a question interaction with Record interactions enabled
2. Publish course with the updated Spoor extension and ensure Record interactions is enabled
3. Upload to a LMS that does not have cmi.interactions._count functionality included
4. No error should appear
=> Fix: Check LMS supports cmi.interactions._count (fixes #294)

js/scorm/wrapper.js
Fixes #300, #283.
* Delay error messaging until all course data is ready.
* Allows other plugins handling errors to listen to error events before they have been fired.
=> Fix: delay error messaging until all course data is ready

js/adapt-stateful-session.js, js/scorm/wrapper.js
Fixes #302.
* Changed logic for 401 error handling so calls to unsupported data elements will fail silently.
=> Fix: Changed logic for 401 error handling

js/scorm/wrapper.js
Fixes #304.
* Amended logic to check for supported `_children` elements before attempting to set values.
=> Fix: Amended logic to check for supported `_children` elements before attempting to set values

js/scorm/wrapper.js
Fixes #307.
* Error logging order to match execution order of SCORM calls.
=> Fix: error logging order to match call execution (fixes #307).

required/index.html, required/index_lms.html, required/scorm_test_harness.html
fixes https://github.com/adaptlearning/adapt-contrib-core/issues/499
* Set initial html lang and dir attributes from _defaultLanguage and _defaultDirection in config.json
=> Fix: set html lang and dir attributes from config.json (fixes #499)

README.md
Fixes #312 
* Fixes several broken links
* Revisions for clarity purposes
* Fix Markdown linting errors like spaces between lines, colons at the end of headings, incorrect emphasis markup, etc.
* Fix line breaks at the end
Suggest viewing the readme file in a [preview](https://code.visualstudio.com/docs/languages/markdown#_markdown-preview) mode.
=> Chore: Readme updates for broken links, clarity, and linting errors (fixes #312)

js/adapt-stateful-session.js, required/log_output.html
Fixes https://github.com/adaptlearning/adapt-contrib-spoor/issues/314
Added the pagehide event next to the unload event with the same behaviour so that end-users won't notice when Google Chrome stops supporting unload. This is the same fix as was applied in the latest version of Spoor https://github.com/adaptlearning/adapt-contrib-spoor/pull/298/files.
To test this I tried removing the unload events entirely and switching to pagehide events. I created and published a course and I was able to see that my progress was saved if I closed the window part-way through.
I'm not sure if there is a process for updating an older version of a plugin like this. I created a release-3.3 branch from the v3.3.2 tag. I have made a pull request to add this fix to the release-3.3 branch and I propose we tag …
=> Fix: Add pagehide event (Fixes #314)

README.md, example.json, js/adapt-offlineStorage-scorm.js, js/adapt-stateful-session.js, js/scorm/wrapper.js, properties.schema, schema/config.schema.json
fixes #316 
* Added `_recordObjectives` config
* Check for objective existence before resetting id
=> Fix: Added cmi.objectives _recordObjectives and id existence check (fixes #316)

js/scorm/wrapper.js
Fixes #320.
*  Set exit state on initialisation to negate SCORM 2004 runtime data being reset on relaunch if disconnected whilst course window is closed.
* Set session time on each commit to prevent this from potentially being lost if [`finish`](https://github.com/adaptlearning/adapt-contrib-spoor/blob/9dbfaff2ee86abb394304c8471fef80d8e09ee2e/js/scorm/wrapper.js#L315) is not called during exit. This can occur due to being disconnected, or potentially when used via a mobile app which may not trigger the required [window events](https://github.com/adaptlearning/adapt-contrib-spoor/blob/9dbfaff2ee86abb394304c8471fef80d8e09ee2e/js/adapt-stateful-session.js#L129).
=> Fix: SCORM 2004 runtime data reset if disconnected on exit

js/adapt-stateful-session.js, js/scorm/wrapper.js
Fixes #281.
* Expanded use of `cmi.interactions` data elements to include more context for reporting purposes. Restricted to SCORM 2004 only as the SCORM 1.2 implementation isn't as well defined or supported by many LMSs.
=> New: expanded use of `cmi.interactions` data elements to include more context for reporting purposes

scorm/2004/imsmanifest.xml
Fixes #322.
* Remove unwanted `imsss:objectives` from manifest.
=> Fix: remove unwanted `imsss:objectives` from manifest

js/scorm/wrapper.js
Fixes #334
* Send session time and exit state during call to finish. Not recorded on exit since https://github.com/adaptlearning/adapt-contrib-spoor/releases/tag/v5.9.10.
=> Fix: send session time and exit state during call to finish

bower.json, package.json, required/index.html, required/index_lms.html, required/scorm_test_harness.html
part of https://github.com/adaptlearning/adapt_framework/issues/3649
requires  https://github.com/adaptlearning/adapt_framework/pull/3650
requires https://github.com/adaptlearning/adapt-contrib-core/pull/622
* Force fresh css according to `@@build.timestamp`
=> New: Use build.timestamp to force css reload

js/scorm/wrapper.js
Fixes #339.
* Infinite loop between `setSessionTime` and `commit` when using `commitOnAnyChange`
=> Fix: infinite loop between `setSessionTime` and `commit` when using `commitOnAnyChange`
