adaptlearning/adapt-contrib-spoor

bower.json
package.json

Bumped version to 1.1.8

---

bower.json
js/serialisers/default.js
package.json

Adds a defer to setting the components to complete

---

js/scorm/API.js

from https://github.com/pipwerks/scorm-api-wrapper
(fixes https://github.com/pipwerks/scorm-api-wrapper/issues/19)

pull in latest version of SCORM_API_wrapper.js 

---

js/serializers/questions.js

This PR  will add component['_isCorrect']  and component['_score']  to the spoor.

Add more information to the spoor

---

js/adapt-offlineStorage-scorm.js

* when spoor_isEnabled: false, stop offlineStorage API calling SCORM functions

ABU-940: Properly disable offlineStorage implementation

---

js/adapt-contrib-spoor.js
js/scorm/wrapper.js

fixes https://adaptlearning.atlassian.net/browse/ABU-985

fix incorrect use of 'this' & correct attempt to call method when should be setting a property

---

README.md

to include something about grunt server-scorm

amended section Client Local Storage

---

js/serializers/scormSuspendDataSerializer.js

Partly fixes issue with textinput and three text boxes with generic answers

Fix: made bit count a factor of 4

---

README.md
bower.json
js/serializers/questions.js
js/serializers/scormSuspendDataSerializer.js

* version bump for v2.0.1
* save and restore fixes
* bring inline with develop

Release/2.0.1 - Version Bump

---

bower.json
properties.schema

Fixes https://github.com/adaptlearning/adapt-contrib-spoor/issues/95

Schema defaults and version increment

---

required/main.html
required/scorm_test_harness.html

a to button

---

js/serializers/scormSuspendDataSerializer.js

This PR will fix an issue for IE8, the issue when we enable _shouldStoreResponses, answer question, close the course and relaunch the course, you will notice that the question has not been saved.

Fix an issue with IE8

---

js/scorm/wrapper.js

Sometimes one need to get access to the student/learner id

Added getStudentId method

---

required/main.html
required/scorm_test_harness.html

main.html was missing the id="adapt" onthe ie conditionals

updating ie conditionals to include adapt id

---

README.md
example.json
js/adapt-contrib-spoor.js
js/adapt-offlineStorage-scorm.js
js/adapt-stateful-session.js
js/scorm/wrapper.js
required/offline_API_wrapper.js

https://adaptlearning.atlassian.net/browse/ABU-690

Added SCORM interactions support (and added basic SCORM 2004 support to offline_API_wrapper.js)

---

js/serializers/questions.js

https://github.com/adaptlearning/adapt-contrib-spoor/issues/117

bugfix/attempts-restore: attemptsLeft restore fix

---

js/scorm/wrapper.js

see https://github.com/adaptlearning/adapt_framework/issues/992

fix incorrect use of _.isEmpty

---

required/index.html
required/index_lms.html
required/main.html

see https://github.com/adaptlearning/adapt_framework/issues/997
remove the 'encoding' meta tag as it is not valid
remove 'language' attribute from script tags, these are not needed
remove 'role' attribute from button tag, it is not needed

updates to allow for better validation

---

js/adapt-offlineStorage-scorm.js

https://github.com/adaptlearning/adapt_framework/issues/1044

issue-1044: return learner_id

---

js/adapt-stateful-session.js

just long enough for all the block completion data to be restored - fixes [#1149](https://github.com/adaptlearning/adapt_framework/issues/1149)
To replicate this issue, launch the out-of-the-box course on an LMS and complete a bunch of components. Then quit and relaunch with the debugger on and you'll see that each time a block has its completion data restored, this triggers a call to set suspend_data:
<details>
<summary>Moodle debug log showing the multiple calls to set suspend_data</summary>
```
Fri, 22 Jul 2016 12:37:56 GMT: LMSInitialize("", "") => 0
Fri, 22 Jul 2016 12:37:56 GMT: LMSGetValue("cmi.core.lesson_status") - incomplete => 0
Fri, 22 Jul 2016 12:37:56 GMT: Commit("", "") => 0
Fri, 22 Jul 2016 12:37:56 GMT: LMSCommit("AJAXResult", "true") => 0
Fri, 22 Jul 2016 12:37:56 GMT: …
```

add a defer call to delay the call to setupEventListeners 

---

js/adapt-stateful-session.js

see [#1203](https://github.com/adaptlearning/adapt_framework/issues/1203)

remove unused code

---

js/adapt-stateful-session.js

In conjunction with https://github.com/adaptlearning/adapt_framework/pull/1253.

Rename language change event

---

js/adapt-contrib-spoor.js

see https://github.com/adaptlearning/adapt-contrib-languagePicker/issues/14

allow offlineStorage to be marked as 'ready' even when spoor is disabled

---

README.md
bower.json
example.json
js/adapt-offlineStorage-scorm.js
js/adapt-stateful-session.js
js/scorm.js
js/scorm/wrapper.js
js/serializers/default.js
js/serializers/questions.js
properties.schema
required/index.html
required/index_lms.html
required/log_output.html
required/main.html

make sure "lang" is always set in suspendDataStore
adds ability to reset session

multilang feature

---

README.md
bower.json
js/adapt-contrib-spoor.js

as per https://github.com/adaptlearning/adapt_framework/issues/1290
also sort out indentation

remove dependency on specific version of framework

---

js/adapt-contrib-spoor.js
js/adapt-stateful-session.js
js/scorm/wrapper.js

as per https://github.com/adaptlearning/adapt_framework/issues/1368

add beforeunload handlers

---

js/adapt-stateful-session.js

This facilitates submitting a non-percentage based score to the LMS.

Re-factored submitScore() to check isPercentageBased property

---

README.md
bower.json
js/adapt-contrib-spoor.js
js/adapt-stateful-session.js
js/serializers/default.js
required/offline_API_wrapper.js

as per https://github.com/adaptlearning/adapt_framework/pull/1113#issuecomment-263248901

setup spoor to pause course initialisation/routing (IE8 performance improvement)

---

js/serializers/scormSuspendDataSerializer.js
required/offline_API_wrapper.js

https://github.com/adaptlearning/adapt_framework/issues/1535

issues-1535: remove cookie url encoding

---

js/serializers/questions.js

https://github.com/adaptlearning/adapt_framework/issues/1586

issue/1586: fix zero length array save

---

properties.schema

adds `_shouldRecordInteractions` into the schema to fix [#1494](https://github.com/adaptlearning/adapt_framework/issues/1494) 
also switch drop downs to checkboxes since it seems daft to make the user click twice to change the selection
amends to help text, spacing

schema updates

---

required/offline_API_wrapper.js

Fixes https://github.com/adaptlearning/adapt_framework/issues/1619.
N.B. respects `_spoor._advancedSettings._suppressErrors` if set (using `console.error` in preference to `alert`).

Implemented detection of when storage limit exceeded

---

js/adapt-offlineStorage-scorm.js
js/scorm/wrapper.js

in the appropriate SCORM data element (where supported) - see https://github.com/adaptlearning/adapt_framework/issues/1404

add support for storing the user's choice of language

---

required/index.html
required/index_lms.html
required/scorm_test_harness.html

Dependency of https://github.com/adaptlearning/adapt_framework/pull/1830

Removed accessibility toggle button and instructions

---

required/index.html
required/index_lms.html
required/scorm_test_harness.html

https://github.com/adaptlearning/adapt_framework/issues/1942
* changed `adapt/css/adapt.css` to `adapt.css`
* update `scorm_test_harness.html` meta tags to match `index.html`

issue/1942: switched to adapt.css

---

js/adapt-stateful-session.js

As part of the rework in components to split model and view functions, with this code the model will be checked (when available) for the following functions:
- getResponseType()
- getResponse()
- isCorrect()

Fixes #1990, update to onQuestionRecordInteraction() to call model functions

---

required/offline_API_wrapper.js

https://github.com/adaptlearning/adapt_framework/issues/1905

issue/1905: stopped cmi.interactions in offline_API

---

js/adapt-contrib-spoor.js

fixes issue https://github.com/adaptlearning/adapt_framework/issues/1823

issue/1823: utilise Adapt.wait

---

README.md
bower.json
example.json
js/adapt-contrib-spoor.js
js/adapt-stateful-session.js
properties.schema
required/index.html
required/index_lms.html

merge all recent PRs into master

---

required/index.html
required/index_lms.html

part of https://github.com/adaptlearning/adapt_framework/issues/2033

add 'dir' attribute

---

js/scorm/wrapper.js
libraries/SCORM_API_wrapper.js

https://github.com/adaptlearning/adapt_framework/issues/2222

Amend to fix potential Commit issue when unloading browser in SCORM 2004

---

example.json
js/adapt-contrib-spoor.js
js/adapt-offlineStorage-scorm.js
js/adapt-stateful-session.js
js/scorm.js
js/scorm/logger.js
js/scorm/wrapper.js
js/serializers/default.js
js/serializers/questions.js
js/serializers/scormSuspendDataSerializer.js

Spoor converted to use 2 spaces for indentation.
I haven't touched any of the library or required files as these are usually copy/paste replacements.

update to use 2 spaces for indentation

---

bower.json
js/scorm/wrapper.js

Fixes https://github.com/adaptlearning/adapt_framework/issues/2537

Issue 2537 Setting context for the handleError call

---

required/index.html
required/index_lms.html
required/scorm_test_harness.html

it hasn't prevented pinch-zooming on iOS since v10

amend viewport meta tag

---

js/serializers/questions.js
properties.schema

Reverts adaptlearning/adapt-contrib-spoor#189

Revert "issue/2747 Added _attemptStates save and restore"

---

js/scorm/wrapper.js

fixes https://github.com/adaptlearning/adapt_framework/issues/2927

set default values for the _minScore & _maxScore parameters of setScore

---

js/scorm/wrapper.js

resolves https://github.com/adaptlearning/adapt_framework/issues/2962

trigger event whenever LMSCommit is called

---

js/adapt-offlineStorage-scorm.js

resolves https://github.com/adaptlearning/adapt_framework/issues/2972

amend save so that it triggers LMSCommit

---

libraries/js-cookie.js
required/offline_API_wrapper.js
required/scorm_test_harness.html

* refactor offline_API_wrapper.js to remove some duplication
* add cookie settings into scorm_test_harness.html with comments
resolves https://github.com/adaptlearning/adapt_framework/issues/2798

update from jquery-cookie to js-cookie

---

js/scorm/wrapper.js

fixes https://github.com/adaptlearning/adapt_framework/issues/3049

set correct error type in commit function

---

example.json
js/scorm/error.js
js/scorm/wrapper.js

fixes https://github.com/adaptlearning/adapt_framework/issues/3048

check for error code when LMSFinish/Terminate fails

---

README.md
js/adapt-stateful-session.js

fixes https://github.com/adaptlearning/adapt_framework/issues/3104
* Made `printCompletionInformation(suspendData)` able to convert any course suspend data to a completion string 
* Updated readme

issue/3104 Made printCompletionInformation course independent

---

required/index.html
required/index_lms.html
required/scorm_test_harness.html

https://github.com/adaptlearning/adapt_framework/issues/3151
* `window.ADAPT_BUILD_TYPE` for `production` or `development` flagging

issue/3151 Added window.ADAPT_BUILD_TYPE flag

---

required/offline_API_wrapper.js

fixes #220 
* Made api construction synchronous

issue/220 Fix fetch is not a function bug

---

bower.json
js/adapt-stateful-session.js

Fixes https://github.com/adaptlearning/adapt_framework/issues/2604
See https://github.com/adaptlearning/adapt-contrib-core/pull/30

#2604 ensure score sent to LMS before status

---

bower.json
js/adapt-contrib-spoor.js
js/adapt-offlineStorage-scorm.js
js/adapt-stateful-session.js
js/scorm/error.js
js/scorm/logger.js
js/scorm/wrapper.js
js/serializers/ComponentSerializer.js
js/serializers/SCORMSuspendData.js

[#2808](https://github.com/adaptlearning/adapt_framework/issues/2808)

2808 convert to es6 classes

---

schema/config.schema.json

https://github.com/adaptlearning/adapt-contrib-core/issues/55
* _shouldSubmitScore from schema

issue/55 Removed _shouldSubmitScore from schema

---

properties.schema

fixes #225 
* _shouldSubmitScore from legacy schema

issue/225 Removed _shouldSubmitScore from legacy schema

---

js/serializers/ComponentSerializer.js

fixes #236 
* Tracking indices moving out by one when using trickle
See https://github.com/adaptlearning/adapt-contrib-core/pull/131

issue/236 Filter _isTrackable === false before save/restore

---

required/index.html
required/index_lms.html
required/scorm_test_harness.html

part of https://github.com/adaptlearning/adapt_framework/issues/3311
* Removed unnecessary type attribute on script tags

issue/3311 Removed unnecessary type attribute on script tags

---

js/adapt-stateful-session.js

https://github.com/adaptlearning/adapt-contrib-spoor/issues/234
* Ensure cmi.interactions.n.id is unique

Ensure cmi.interactions.n.id is unique (fixes #234)

---

README.md
example.json
js/adapt-stateful-session.js
properties.schema

Fixes #242.
* Added ability to configure `_setCompletedWhenFailed` for SCORM 2004

New: Added ability to configure `_setCompletedWhenFailed`.

---

properties.schema
schema/config.schema.json

Fix: Amend default schema value for `_setCompletedWhenFailed`

---

js/scorm/wrapper.js

Fixes #288 
* Overriding the set maxLength if override passed

Fix: Overriding the set maxLength if override passed

---

bower.json
package.json

Previous commit was not in the correct format

Fix: Version patch bump

---

js/scorm/wrapper.js

Fix #291 
* Close loading screen via router.hideLoading()

Fix: Close loading screen via router.hideLoading() (fixes #291)

---

migrations/v2.js
migrations/v3.js
migrations/v4.js
migrations/v5.js

Fixes #324.
* Added migration scripts.

New: added migration scripts

---

js/adapt-contrib-spoor.js

#327 
* import jquery.keycombo amended to avoid being included in compile (fixes #327)

Fix: import jquery.keycombo amended to avoid being included in compile (fixes #327)

---

required/index.html
required/index_lms.html
required/scorm_test_harness.html

Fixes #337 
* Add a static `html` class the html element

Fix: Add html class to html element (fixes #337)
